Tried to add Goertzel detection routine, but getting nonsensical error.
	- goertzel_detection_mode.cpp:11:28: error: no matching function
	  for call to 'Goertzel::Goertzel()'
		- This doesn't make any sense, because this is never called
		  in this manner. It's always got three floats in it.